name: CI
on: [push, pull_request]
jobs:
  checkov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install checkov
      - run: checkov -d terraform/insecure --compact --soft-fail
      - run: checkov -d terraform/secure --compact --soft-fail
